apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: babench/hipster-frontend:0.1
    name: frontend
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3001"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:3002"
      - name: CART_SERVICE_ADDR
        value: "cartservice:3003"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:3004"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:3005"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:3006"
      - name: AD_SERVICE_ADDR
        value: "adservice:3007"
